### PR TITLE
Multithreading Compatibility

### PR DESCRIPTION
**Pull request by Asap7772**
## What is done
- Mail doesn't hang the main thread anymore

### CODE REVIEW

**Comment by Asap7772** [comment]
Hopefully this works!

**Comment by Zedai** [comment]
Wait, why do I have write access here?

**Comment by Zedai** [comment]
nvm its the other repository i'm dumb

**Comment by cuuush** [comment]
I like what you added, so I used some of your changes to make plugins work. Check [the readme](https://github.com/chriscush765/hellogit/blob/master/README.md) to see what changes need to be added.

**Comment by protanop1c** [comment]
haha nice 🤔

**Comment by Zedai** [comment]
Watch us run into Chao at Five Guys again

**Pull request closed without merging**
